set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER $ENV{NDK_HOME}/toolchains/$ENV{NDK_TOOLCHAIN}-$ENV{GCC_VERSION}/prebuilt/linux-x86_64/bin/$ENV{NDK_TOOLCHAIN}-gcc)
set(CMAKE_CXX_COMPILER $ENV{NDK_HOME}/toolchains/$ENV{NDK_TOOLCHAIN}-$ENV{GCC_VERSION}/prebuilt/linux-x86_64/bin/$ENV{NDK_TOOLCHAIN}-g++)

set(CMAKE_SYSROOT $ENV{NDK_HOME}/platforms/android-$ENV{ANDROID_VERSION}/arch-$ENV{NDK_ARCH})