set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER $ENV{ARM_TOOLCHAIN_HOME}/bin/$ENV{ARM_TOOLCHAIN}-gcc)
set(CMAKE_CXX_COMPILER $ENV{ARM_TOOLCHAIN_HOME}/bin/$ENV{ARM_TOOLCHAIN}-g++)

set(CMAKE_SYSROOT $ENV{ARM_TOOLCHAIN_HOME}/$ENV{ARM_TOOLCHAIN}/libc)
